# Base and Name
FROM debian AS make
LABEL name dev_env

# Install Python and Django
RUN apt update 
RUN apt install -y python3 python3-pip python3-django

# Use unprivileged user and copy our directory.
RUN useradd -m rtt_backend
USER rtt_backend
WORKDIR /home/rtt_backend

# Run the server in the controlled environment as the default action.
CMD python3 -m manage runserver 0.0.0.0:8000

# Use run.sh to run the server properly.


