# Base and Name
FROM ubuntu AS make
LABEL name dev_env_front

# <Add Frontend Installs Here>

# Use unprivileged user and copy our directory.
RUN useradd -m rtt_frontend
USER rtt_frontend
WORKDIR /home/rtt_frontend

# <Add Frontend Run Here>

# Use the script to run the server properly.


